openai:
  # OPENAI API-KEY
  api-key: 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
  # MODEL
  model: gpt-3.5-turbo
  # URL
  url: https://api.openai.com/v1/chat/completions
user:
  # 赠送给用户的免费提问次数
  free-ask-count: 5